# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6977241ee76333f90d761530657925798220fafd91be17edf85746ad9aacfc949d88bceb70418d1f9f36d74211cf6714e547c1e1875de3d6c1e9641b9d74f4

test:
  secret_key_base: f855eb3bce89664a388cf4cb6ebecad0731b86f502bec3f4f07c479a5dd1e404f5a87a6d33f12ecb3c074a6e8570d43d4d504e35e3e1fcb93fde164e9cdf7ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
